name: mioxi_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0 # Verifica la última versión disponible
  get: ^4.7.2
  #flutter_reactive_ble: ^5.4.0
  #permission_handler: ^11.3.1  # ← agrega esto
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^30.1.38
  shared_preferences: ^2.0.15
  #collection: ^1.18.0


dev_dependencies:
  multi_select_flutter: ^4.0.0
  flutter_test:
    sdk: flutter
  get_storage: ^2.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/others/images/SpO.png
    - lib/others/images/SpODark.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/others/fonts/OpenSans-Regular.ttf
        - asset: lib/others/fonts/OpenSans-Bold.ttf
          weight: 700
 